#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#44475a'

picom &
blueberry-tray &
nm-applet &
#light-locker &
xscreensaver -no-splash &
#shutter &

#if ! pgrep -x "volumeicon" > /dev/null
#then
#volumeicon &
#fi

killall volumeicon
volumeicon &

killall cerebro
/home/brody/Applications/cerebro &

nitrogen --restore

#xfce4-panel --sm-client-disable &

myTerm=alacritty

hc pad 0 37 0 0 0
hc set focus_stealing_prevention off

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit #quit WM
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
#hc keybind $Mod-Return spawn "${TERMINAL:-xterm}" # use your $TERMINAL with xterm as fallback
hc keybind $Mod-Return spawn $myTerm
#hc keybind $Mod-b spawn microsoft-edge-beta --use-gl=desktop --enable-features=VaapiVideoDecoder --disable-features=UseChromeOSDirectVideoDecoder
hc keybind $Mod-b spawn brave
hc keybind $Mod-Shift-b spawn google-chrome-stable --use-gl=desktop --enable-features=VaapiVideoDecoder --disable-features=UseChromeOSDirectVideoDecoder
hc keybind $Mod-e spawn libreoffice
#hc keybind $Mod-space spawn rofi -show run
hc keybind $Mod-space spawn dmenu_run -l 25 -g 3 -bw 3 -fn "FiraCode Nerd Font:style=Regular:size=18"
#hc keybind $Mod-space spawn dmenu_run -c -l 20 -nb '#6373a4' -nf '#f8f8f2' -sb '#8be9fd' -sf '#44475a' -p 'dmenu:'
hc keybind $Mod-Shift-space spawn pcmanfm
#hc keybind $Mod-Shift-space spawn thunar
hc keybind $Mod-Control-Shift-Escape spawn xscreensaver-command -activate
#hc keybind $Mod-Alt-Escape spawn light-locker-command -l
hc keybind $Mod-Alt-Escape spawn xscreensaver-command -activate
#hc keybind $Mod-Alt-Escape spawn dm-tool switch-to-greeter
hc keybind $Mod-d spawn Discord
hc keybind $Mod-n spawn joplin
hc keybind $Mod-m spawn /usr/local/bin/thunderbird

# media controls - tied to ALT keyboard
hc keybind XF86AudioPlay spawn playerctl play-pause
hc keybind XF86AudioForward spawn playerctl next
hc keybind XF86AudioRewind spawn playerctl previous

# basic movement in tiling and floating mode
# focusing clients
hc keybind $Mod-period focus right
hc keybind $Mod-comma focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5

# let the current frame explode into subframes
# hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
#tag_names=( "" "" "" "" "" "" "" "" "")     
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-Left  use_index -1 --skip-visible
hc keybind $Mod-Right use_index +1 --skip-visible
hc keybind $Mod-Control-Tab  use_index +1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s fullscreen toggle
#hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f floating toggle
hc keybind $Mod-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-d set_attr clients.focus.decorated toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-p pseudotile toggle

# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
# hc keybind $Mod-Control-space
#            or , and . compare tags.focus.curframe_wcount = 2                   \
#                     . cycle_layout +1 vertical horizontal max vertical grid    \
#               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-Backspace   cycle_monitor
hc keybind $Mod-Escape  use_index +1 --skip-visible
hc keybind $Mod-Shift-Escape  use_index -1 --skip-visible
#hc keybind $Mod-Tab         cycle_all +1
#hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-Tab        cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#bd93f9'
hc set frame_border_normal_color '#6272a4'
#hc set frame_bg_normal_color '#44475a'
hc set frame_bg_active_color '#8be9fd'
hc set frame_border_width 3
#hc set show_frame_decorations 'focused_if_multiple'
hc set frame_bg_transparent on
hc set frame_transparent_width 0
hc set frame_gap 10

#hc attr theme.title_height 0
hc attr theme.title_when never
hc attr theme.active.color '#8be9fd'
hc attr theme.title_color '#ffffff'
hc attr theme.normal.color '#6272a4'
hc attr theme.urgent.color '#ffb86c'
#hc attr theme.tab_color '#1F1F1Fdd'
#hc attr theme.active.tab_color '#2B4F0Add'
#hc attr theme.active.tab_outer_color '#6C8257dd'
#hc attr theme.active.tab_title_color '#ababab'
#hc attr theme.normal.title_color '#898989'
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 2
hc attr theme.floating.border_width 1
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
#hc attr theme.active.inner_color '#8be9fd'
#hc attr theme.urgent.inner_color '#ffb86c'
#hc attr theme.normal.inner_color '#6272a4'

# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
hc attr theme.tiling.outer_width 0
hc attr theme.background_color '#44475a'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings off
hc set mouse_recenter_gap 0

# rules
hc unrule -F
hc rule focus=on # normally focus new clients
hc rule floatplacement=center
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on
hc rule instance="google-chrome" tag="3" # move chrome to tag 
hc rule instance="microsoft-edge" tag="4" # move edge to tag 
hc rule instance="microsoft-edge-beta" tag="4" # move edge to tag 
hc rule instance="Navigator" tag="5" # move firefox to tag 
hc rule instance="brave-browser" tag="4" # move brave to tag 
hc rule instance="okular" tag="6" # move okular to tag 
hc rule instance="cider" tag="6" # move cider to tag 
hc rule instance="Mail" tag="7" # move thunderbird to tag 
hc rule instance="joplin" tag="6" # move joplin to tag 
hc rule instance="code" tag="8" # move code to tag 
hc rule instance="zoom " tag="9" # move zoom to tag 
hc rule instance="discord" tag="9" # move discord to tag 
hc rule instance="slack" tag="9" # move discord to tag 

# floating window rules
hc rule instance="galculator" floating=on floatplacement=center
hc rule instance="calc" floating=on floatplacement=center
hc rule instance="qalculate-gtk" floating=on floatplacement=center
hc rule instance="system-config-printer" floating=on floatplacement=center
hc rule instance="discord" floating=off floatplacement=center
hc rule instance="zoom " floating=on floatplacement=center # float all zoom windows
hc rule instance="lightdm-gtk-greeter-settings" floating=on floatplacement=center
hc rule instance="xscreensaver-settings" floating=on floatplacement=center
hc rule instance="pavucontrol" floating=on floatplacement=center
hc rule instance="shutter" floating=on floatplacement=center
hc rule instance="nm-openconnect-auth-dialog" floating=on floatplacement=center
hc rule instance="font-manager" floating=on floatplacement=center
#hc rule instance="blueberry.py" floating=on floatplacement=center
hc rule instance="volumeicon" floating=on floatplacement=center
hc rule instance="xfce4-panel" floating=on floatplacement=center
hc rule instance="wrapper-2.0" floating=on floatplacement=center
hc rule instance="gp-saml-gui" floating=on floatplacement=center
hc rule windowrole="pop-up" floating=on floatplacement=center floating_geometry="1200x900" tag="" # gmail popups
hc rule instance="Msgcompose" floating=on floatplacement=center floating_geometry="1200x900" tag="" # thunderbird popup
hc rule instance="blueberry.py" floating=on floatplacement=center
hc rule instance="nm-connection-editor" floating=on floatplacement=center
hc rule instance="org.remmina.Remmina" floating=on floatplacement=center
hc rule instance="vmrc" floating=on floatplacement=center
hc rule instance="cider" floating=on floatplacement=center
hc rule pid="2140008" floating=on floatplacement=center # zoom alert pop-ups
hc rule instance="lxappearance" floating=on floatplacement=center
#hc rule instance="org.gnome.DejaDup" floating=on floatplacement=center

# layout style
hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

killall polybar
# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
"$panel"

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

#for monitor in $(hc list_monitors | cut -d: -f1) ; do
#    # start it on each monitor
#    "$panel" "$monitor" &
#done
